apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: gpac-chaos-ddebowski-new2
  namespace: ddebowski
spec:
  phases:
    - duration: PT1M
      actions:
        - namespace: ddebowski
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: ddebowski
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer1-dep
          scaleDeploymentSpec:
            value: 0
    - duration: PT1M
      actions:
        - namespace: ddebowski
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: ddebowski
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: ddebowski
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer2-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: ddebowski
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer2-dep
          scaleDeploymentSpec:
            value: 0
