apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: gpac-chaos-rszuma
  namespace: rszuma
spec:
  phases:
    - duration: PT5M
      actions:
        - namespace: rszuma
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: rszuma
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer1-dep
          scaleDeploymentSpec:
            value: 0
    - duration: PT5M
      actions:
        - namespace: rszuma
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: rszuma
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: rszuma
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer2-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: rszuma
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer2-dep
          scaleDeploymentSpec:
            value: 0
