apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: gpac-chaos-kjarosz
  namespace: kjarosz
spec:
  phases:
    - duration: PT5M
      actions:
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer2-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer2-dep
          scaleDeploymentSpec:
            value: 0
    - duration: PT5M
      actions:
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer2-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer3-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer4-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer5-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset0-peer6-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer1-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer2-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer3-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer4-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer5-dep
          scaleDeploymentSpec:
            value: 0
        - namespace: kjarosz
          resourceType: deployment
          action: scale
          resourceName: peerset1-peer6-dep
          scaleDeploymentSpec:
            value: 0
