version: "3.3"

services:
  _image_build:
    image: poc
    entrypoint: /bin/bash
    command: 'echo build completed'
    build:
      context: .
      dockerfile: Dockerfile
  peer1:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8081:8080"
      - "10024"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_host: "peer1"
      config_peerId: "1"
      config_peersetId: "1"
  peer2:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8082:8080"
      - "10124"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_host: "peer2"
      config_peerId: "2"
      config_peersetId: "1"
  peer3:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8083:8080"
      - "11124"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_host: "peer3"
      config_peerId: "3"
      config_peersetId: "1"
  peer4:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8084:8080"
      - "10034"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_host: "peer4"
      config_peerId: "1"
      config_peersetId: "2"
  peer5:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8085:8080"
      - "10134"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_host: "peer5"
      config_peerId: "2"
      config_peersetId: "2"
  peer6:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8086:8080"
      - "11134"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_host: "peer6"
      config_peerId: "3"
      config_peersetId: "2"
