version: "3.3"

services:
  _image_build:
    image: poc
    entrypoint: /bin/bash
    command: 'echo build completed'
    build:
      context: .
      dockerfile: Dockerfile.builder
  peer1:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8081:8080"
      - "10024"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_peerId: "0"
      config_peersetId: "0"
  peer2:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8082:8080"
      - "10124"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_peerId: "1"
      config_peersetId: "0"
  peer3:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8083:8080"
      - "11124"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_peerId: "2"
      config_peersetId: "0"
  peer4:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8084:8080"
      - "10034"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_peerId: "0"
      config_peersetId: "1"
  peer5:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8085:8080"
      - "10134"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_peerId: "1"
      config_peersetId: "1"
  peer6:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8086:8080"
      - "11134"
    environment:
      CONFIG_FILE: "application-compose.conf"
      config_peerId: "2"
      config_peersetId: "1"
