version: "3.3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  _image_build:
    image: poc
    entrypoint: /bin/bash
    command: 'echo build completed'
    build:
      context: .
      dockerfile: Dockerfile
  peer1:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8081:8080"
      - "10024"
    environment:
      - RAFT_NODE_ID=1
      - PEERSET_ID=1
      - CONFIG_FILE=application-compose.conf
      - application_environment = "docker_compose"
  peer2:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8082:8080"
      - "10124"
    environment:
      - RAFT_NODE_ID=2
      - PEERSET_ID=1
      - CONFIG_FILE=application-compose.conf
      - application_environment = "docker_compose"
  peer3:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8083:8080"
      - "11124"
    environment:
      - RAFT_NODE_ID=3
      - PEERSET_ID=1
      - CONFIG_FILE=application-compose.conf
      - application_environment = "docker_compose"
  peer4:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8084:8080"
      - "10034"
    environment:
      - RAFT_NODE_ID=1
      - PEERSET_ID=2
      - CONFIG_FILE=application-compose.conf
      - application_environment = "docker_compose"
  peer5:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8085:8080"
      - "10134"
    environment:
      - RAFT_NODE_ID=2
      - PEERSET_ID=2
      - CONFIG_FILE=application-compose.conf
      - application_environment = "docker_compose"
  peer6:
    image: poc
    depends_on:
      - _image_build
    ports:
      - "8086:8080"
      - "11134"
    environment:
      - RAFT_NODE_ID=3
      - PEERSET_ID=2
      - CONFIG_FILE=application-compose.conf
      - application_environment = "docker_compose"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/compose:/etc/prometheus/
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
