global:
  scrape_interval: 20s

scrape_configs:
  - job_name: "prometheus job"
    metrics_path: "/_meta/metrics"
    static_configs:
      - targets: ["localhost:8081", "localhost:8082", "localhost:8083"]