{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ktor_http_server_requests_active, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS on /v2/change/async",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ktor_http_server_requests_seconds_count{route=\"/v2/change/async\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS on processed changes (lowest resolution)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(change_processed_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conflicted changes (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(change_processed_total{result=\"conflict\", namespace=\"$namespace\"}) by (protocol)) or vector(0)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "% of confliced changes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(change_processed_total{result=\"conflict\", namespace=\"$namespace\"}) / sum(change_processed_total{namespace=\"$namespace\"})) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg commit latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(change_processing_time_seconds_sum{result=\"success\", namespace=\"$namespace\"}[125s]) / rate(change_processing_time_seconds_count{result=\"success\", namespace=\"$namespace\"}[125s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=~\"peer.*\", namespace=\"$namespace\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"peer.*\", namespace=\"$namespace\"}[30s]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"performance-test.*\", namespace=\"$namespace\"}[30s]))",
     "legendFormat": "performance tests"
    }
   ]
  },
  {
   "title": "AVG Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"peer.*\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods restarts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}