apiVersion: v1
kind: Deployment
metadata:
  name: "peer1_from_peerset1_deployment" # TODO sth like peer_n_from_peerset_k_deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "peer1_from_peerset1" # TODO - name of pod
  replicas: 1
  template:
    metadata:
      name: "peer1_from_peerset1" # TODO
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/_meta/metrics'
        prometheus.io/port: '8080'
    spec:
      - name: "peer1_from_peerset1" # TODO - sth like peer_n_from_peerset_k
        image: davenury/ucac
        ports:
          - containerPort: 8080
            name: application-port
        envFrom:
          - configMapRef:
              name: peer-config