apiVersion: v1
kind: Service
metadata:
  name: "peer1-from-peerset1-service"
  namespace: "tryout"
spec:
  selector:
    #app.kubernetes.io/name: "peer1-from-peerset1"
    peerId: "1"
    peersetId: "1"
  ports:
    - port: 8080
      targetPort: 8080