apiVersion: v1
kind: Service
metadata:
  name: "peer1_from_peerset1_service" # TODO sth like peer_n_from_peerset_k_service
spec:
  selector:
    app.kubernetes.io/name: "peer1_from_peerset1" # TODO - name of pod
  ports:
    - port: 8080
      targetPort: 8080