apiVersion: v1
kind: Service
metadata:
  name: "peer1-from-peerset1-service" # TODO sth like peer_n_from_peerset_k_service
  namespace: "tryout"
spec:
  selector:
    #app.kubernetes.io/name: "peer1-from-peerset1" # TODO - name of pod
    peerId: "1"
    peersetId: "1"
  ports:
    - port: 8080
      targetPort: 8080