name: Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: build/reports/
      
      - name: Build and publish image
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        with:
          github-push-secret: ${{ secrets.DOCKER_DEPLOYMENT_TOKEN }}
          docker-image-name: davenury/ucac
          docker-image-tag: "${{ $GITHUB_REF == 'refs/heads/main' && 'latest' || $GITHUB_SHA }}"
          dockerfile-path: ./Dockerfile # TODO - change after two separate dockerfiles
          build-context: .
