name: Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports1
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports2
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports3
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports4
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports5
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports6
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports7
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports8
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports9
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports10
          path: |
            build/reports/
            build/test-results/


      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports11
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports12
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports13
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports14
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports15
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports16
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports17
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports18
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports19
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports20
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports21
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports22
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports23
          path: |
            build/reports/
            build/test-results/

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports24
          path: |
            build/reports/
            build/test-results/