name: K8s

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: install k8s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: build command
        working-directory: ./cmd
        run: go get && go build -o cmd
      - name: deploy pods
        working-directory: ./cmd
        run: ./cmd deploy -n test --create-namespace --peers=3,1
      - name: wait for deploy
        run: sleep 15
      - name: test command
        working-directory: ./cmd
        run: ./cmd test -n test
      - name: cleanup pods
        working-directory: ./cmd
        run: ./cmd cleanup -n test
