name: K8s

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Build and publish image
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        with:
          github-push-secret: ${{ secrets.DOCKER_DEPLOYMENT_TOKEN }}
          docker-image-name: ucac
          docker-image-tag: "${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}"
          dockerfile-path: ./Dockerfile.builder
          build-context: .

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@v0.0.8
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: build command
        working-directory: ./cmd
        run: go get && go build -o cmd
      - name: deploy pods
        working-directory: ./cmd
        run: ./cmd deploy -n test --create-namespace --peers=3,1 --wait-for-readiness --image ghcr.io/davenury/ucac:${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
      - name: test command
        working-directory: ./cmd
        run: ./cmd test -n test
      - name: cleanup pods
        working-directory: ./cmd
        run: ./cmd cleanup -n test
